# Generated by Django 5.0.3 on 2024-03-09 13:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBeat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='PreferenceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'PreferencesTags',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Targets',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('discription', models.CharField(max_length=300)),
                ('is_online', models.BooleanField(default=False)),
                ('active_in_search', models.BooleanField()),
                ('last_coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('contact_data', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.gender')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.user')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Disike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
            ],
            options={
                'db_table': 'Disikes',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
                ('second_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
            ],
            options={
                'db_table': 'Connections',
            },
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.preferencetag')),
            ],
            options={
                'db_table': 'ProfilesTags',
            },
        ),
        migrations.CreateModel(
            name='ProfileTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.profile')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartBeat.target')),
            ],
            options={
                'db_table': 'ProfilesTargets',
            },
        ),
    ]
