# Generated by Django 5.0.3 on 2024-03-09 22:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBeat', '0002_gender_preferencetag_target_profile_like_disike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_in_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326),
        ),
    ]
