# Generated by Django 5.0.3 on 2024-03-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBeat', '0003_alter_profile_active_in_search_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='first_profile_id',
            new_name='first_profile',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='second_profile_id',
            new_name='second_profile',
        ),
        migrations.RenameField(
            model_name='disike',
            old_name='disliked_profile_id',
            new_name='disliked_profile',
        ),
        migrations.RenameField(
            model_name='disike',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_profile_id',
            new_name='liked_profile',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender_id',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profiletag',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profiletag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='profiletarget',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profiletarget',
            old_name='target_id',
            new_name='target',
        ),
    ]
